# Generated by Django 3.0.8 on 2020-07-22 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=9)),
                ('rg', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=11)),
                ('ativo', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
    ]
