# Generated by Django 3.0.8 on 2020-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200722_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('cpf', 'rg')},
        ),
    ]
