# Generated by Django 3.0.8 on 2020-07-24 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20200723_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
