# Generated by Django 3.0.8 on 2020-07-24 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20200724_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(blank=True, default=datetime.datetime.now, editable=False),
        ),
    ]
